namespace PlayNirvanaTechExam;

public enum SecondaryHoursType
{
    SECONDARY_HOURS_TYPE_UNSPECIFIED,
    DRIVE_THROUGH,
    HAPPY_HOUR,
    DELIVERY,
    TAKEOUT,
    KITCHEN,
    BREAKFAST,
    LUNCH,
    DINNER,
    BRUNCH,
    PICKUP,
    ACCESS,
    SENIOR_HOURS,
    ONLINE_SERVICE_HOURS
}

public enum BusinessStatus
{
    BUSINESS_STATUS_UNSPECIFIED,
    OPERATIONAL,
    CLOSED_TEMPORARILY,
    CLOSED_PERMANENTLY
}

public enum PriceLevel
{
    PRICE_LEVEL_UNSPECIFIED,
    PRICE_LEVEL_FREE,
    PRICE_LEVEL_INEXPENSIVE,
    PRICE_LEVEL_MODERATE,
    PRICE_LEVEL_EXPENSIVE,
    PRICE_LEVEL_VERY_EXPENSIVE
}

public enum FuelType
{
    FUEL_TYPE_UNSPECIFIED,
    DIESEL,
    DIESEL_PLUS,
    REGULAR_UNLEADE,
    MIDGRADE,
    PREMIUM,
    SP91,
    SP91_E10,
    SP92,
    SP95,
    SP95_E10,
    SP98,
    SP99,
    SP100,
    LPG,
    E80,
    E85,
    E100,
    METHANE,
    BIO_DIESEL,
    TRUCK_DIESEL
}

public enum EVConnectorType
{
    EV_CONNECTOR_TYPE_UNSPECIFIED,
    EV_CONNECTOR_TYPE_OTHER,
    EV_CONNECTOR_TYPE_J1772,
    EV_CONNECTOR_TYPE_TYPE_2,
    EV_CONNECTOR_TYPE_CHADEMO,
    EV_CONNECTOR_TYPE_CCS_COMBO_1,
    EV_CONNECTOR_TYPE_CCS_COMBO_2,
    EV_CONNECTOR_TYPE_TESLA,
    EV_CONNECTOR_TYPE_UNSPECIFIED_GB_T,
    EV_CONNECTOR_TYPE_UNSPECIFIED_WALL_OUTLET,
    EV_CONNECTOR_TYPE_NACS
}

public enum SpatialRelationship
{
    NEAR,
    WITHIN,
    BESIDE,
    ACROSS_THE_ROAD,
    DOWN_THE_ROAD,
    AROUND_THE_CORNER,
    BEHIND
}

public enum Containment
{
    CONTAINMENT_UNSPECIFIED,
    WITHIN,
    OUTSKIRTS,
    NEAR
}
